name: Publish server image to github package
on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
        
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for server image
        id: meta-server
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}-server
          tags: |
            type=semver,pattern={{version}}

      - uses: olegtarasov/get-tag@v2.1
        id: tagName
        with:
          tagRegex: "v(.*)"

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./server
          push: true
          tags: ${{ steps.meta-server.outputs.tags }}
          build-args: VERSION=${{ steps.tagName.outputs.tag }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-cron
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}-cron
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./server
          file: ./server/Dockerfile-cron
          push: true
          tags: ${{ steps.meta-cron.outputs.tags }}
