name: Deploy ViteMaPompe backend
on:
  release:
    types: [published]

jobs:
  deploy_functions:
    name: Deploy Appwrite function to prod
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - uses: appwrite/setup-for-actions@4b9941895ac75e3920788d2df96539e6b54f8bb7
        with:
          endpoint: 'https://${{ secrets.PROD_HOSTNAME }}/v1'
          project: '${{ secrets.PROJECT_ID }}'
          key: '${{ secrets.APPWRITE_API_KEY }}'
      - name: Deploy functions
        run: appwrite deploy function --all
